// Generated by tools/gen_radar.py — do not edit by hand.
// Calibration from resource/overviews/<name>.txt (CS2 VPK):
//   rot 0: worldX = posX + u*scale, worldY = posY - v*scale
//   rot 1: worldX = posY - v*scale, worldY = posX + u*scale
// Verified against spawn setpos ground truth (dust2/mirage/anubis).
#pragma once

struct RadarCal {
    const char* name;    // game map name (globalvars)
    float       posX;    // overview txt: upper-left world coord
    float       posY;
    float       scale;   // world units per art pixel
    int         rot;     // 0 = classic, 1 = 90 deg image variant
    float       lowerZ;  // local z <= lowerZ draws _lower art
    int         origW;   // full-res art px the txt scale refers to;
    int         origH;   //   the shipped bmp is a resample of that rect
};

static const RadarCal kRadarCals[] = {
    { "ar_baggage", -1316.0f, 1288.0f, 2.539062f, 1, -5.0f, 1024, 1024 },
    { "ar_shoots", -1368.0f, 1952.0f, 2.687500f, 0, 1e30f, 1024, 1024 },
    { "ar_shoots_night", -1368.0f, 1952.0f, 2.687500f, 0, 1e30f, 1024, 1024 },
    { "cs_italy", -2647.0f, 2592.0f, 4.600000f, 1, 1e30f, 1024, 1024 },
    { "cs_office", -1838.0f, 1858.0f, 4.100000f, 0, 1e30f, 1024, 1024 },
    { "de_ancient", -2953.0f, 2164.0f, 5.000000f, 0, 1e30f, 1024, 1024 },
    { "de_ancient_night", -2953.0f, 2164.0f, 5.000000f, 0, 1e30f, 1024, 1024 },
    { "de_ancient_v1", -2953.0f, 2164.0f, 5.000000f, 0, 1e30f, 1024, 1024 },
    { "de_ancient_v2", -2953.0f, 2164.0f, 5.000000f, 0, 1e30f, 1024, 1024 },
    { "de_anubis", -2796.0f, 3328.0f, 5.220000f, 0, 1e30f, 1024, 1024 },
    { "de_cache", -2000.0f, 3250.0f, 5.500000f, 0, 1e30f, 1024, 1024 },
    { "de_dust2", -2476.0f, 3239.0f, 4.400000f, 1, 1e30f, 1024, 1024 },
    { "de_inferno", -2087.0f, 3870.0f, 4.900000f, 0, 1e30f, 1024, 1024 },
    { "de_inferno_s2", -2087.0f, 3870.0f, 4.900000f, 0, 1e30f, 1024, 1024 },
    { "de_mirage", -3230.0f, 1713.0f, 5.000000f, 0, 1e30f, 1024, 1024 },
    { "de_nuke", -3453.0f, 2887.0f, 7.000000f, 0, -480.0f, 1024, 1024 },
    { "de_overpass", -4831.0f, 1781.0f, 5.200000f, 0, 1e30f, 1024, 1024 },
    { "de_overpass_2v2", -4831.0f, 1781.0f, 5.200000f, 0, 1e30f, 1024, 1024 },
    { "de_train", -2308.0f, 2078.0f, 4.082077f, 0, -50.0f, 1024, 1024 },
    { "de_vertigo", -3168.0f, 1762.0f, 4.000000f, 0, 11720.0f, 1024, 1024 },
    { "workshop_preview", -2071.0f, 711.0f, 1.699219f, 0, 1e30f, 512, 512 },
};
